### ISSUE TITLE
<Speed> should be of type *int*

### ISSUE THREAD

**Issue by WilliamRagstad** [c4ev3/EV3-API#24]
In the [Commands PDF](https://github.com/c4ev3/EV3-API/blob/master/commands.pdf) under Outputs (Motoren) and help, it says that the parameter "\<Speed>" is a char between 0 to 100...
This should be **int** instead...

**Comment by dnlmlr** [comment]
Even though the commands PDF is likely in need of an update, the Speed parameter being a `char` is actually intended. In C, most of the datatypes like `int`  or `short` are defined to have various sizes depending on the system, architecture and compiler. `char` is the exception, as it is defined to be always exactly one byte. Since `char` does not need to necessarily contain an actual ASCII character, it is therefore often used to express a one byte number. If you look into the ev3_output.h, you will find that the current updated version has the speed variables defined as `uint8_t` which is just a typedef to `unsigned char`. In any case, since the required data has to be excatly one byte, `int` is not the right choice here. 

Still it might useful to update the commands.pdf

**Comment by a3f** [comment]
It should probably be `int8_t`.
Apparently, you can use Libreoffice Draw to edit the PDF. If you want to change it, shoot a pull request.
